schema_version: 1

context:
  name: lazyslide-models
  version: "0.1.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/lazyslide_models-${{ version }}.tar.gz
  sha256: 9858fb596cad11d58461f052c5c18edefafd777177cf4093569872319d2e3447

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - uv-dynamic-versioning
    - pip
  run:
    - python >=${{ python_min }}
    - numpy >=2.0.0
    - timm >=1.0.3
    - pytorch >=2.1.0
    - transformers >=4.0.0
    - pandas
    - opencv
    - scipy
    - scikit-image
    - platformdirs

tests:
  - python:
      imports:
        - lazyslide_models
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: The model zoo for LazySlide
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/rendeirolab/lazyslide-models
  repository: https://github.com/rendeirolab/lazyslide-models

extra:
  recipe-maintainers:
    - Mr-Milk
    - SamirMoustafa
